apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: token
  namespace: skills
spec:
  podSelector: 
    matchLabels:
      role: my-role
  securityGroups:
    groupIds:
      - sg-0152adda3b42025bb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  token
  namespace: skills
  labels:
    app:  token
spec:
  selector:
    matchLabels:
      app: token
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  token
    spec:
      containers:
      - name: token
        image: 648911607072.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
        resources:
          requests:
            cpu: 400m
            memory: 700Mi
          limits:
            cpu: 400m
            memory: 700Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: REDIS_HOST
          value: clustercfg.project-cache.afaync.apn2.cache.amazonaws.com
        - name: REDIS_PORT
          value: '6379'
      restartPolicy: Always
